version: '3.8'
services:
  eureka-service:
    build: ./eureka
    ports:
      - 8761:8761
  gateway-service:
    build: ./gateway
    ports:
      - 8083:8083
    depends_on: 
      - eureka-service
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-service:8761/eureka-service




